import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
 import { Fragment } from "react";
import HomePage from "./HomePage";


export default function Home() {

  return (
    <Fragment>
      <Head>
        <title>Shivam Vidhyalay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <HomePage />
      </main>
    </Fragment>
  );
}
